spring.profiles.active=dev

spring.application.name=Error Logger Codenation

# JWT secret and token expiration time (milliseconds)
jwt.secret=codenation
jwt.expiration=2592000

# Gmail configuration on Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=errorloggersquad3@gmail.com
spring.mail.password=
#Set the email password locally.
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
