name: Java CI

on: 
 push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -DskipTests install
    - name: Publish to Registry release
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: squadjoaquina/errorlogger
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
    - name: Publish to Registry latest
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: squadjoaquina/errorlogger
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
